### ISSUE TITLE
Feedback on number bases and search algorithms

### ISSUE THREAD

**Issue by Anisha7** [JericHunter/CS-1.3-Core-Data-Structures#1]
**Number bases**
Your number base tests for encode are failing due to a "NameError: name 'mod' is not defined" error. I'm guessing you changed a variable name (remainder?) and forgot to update 'mod' in the return statement for encode. This causes convert to fail too. 

**Binary search**
Great work on your recursive binary search. Seems like your iterative binary search is off by one. Great work on implementing a recursive binary search! Your iterative version seems to have some errors. Try printing what indices the midpoint function is getting to (does it ever check 0?) for the test case that is failing, and see if the error is in the midpoint algorithm or the while loop.

**Comment by JericHunter** [comment]
I fixed the name error, you were right I didn't change my var name appreciate you pointing that out. I also fixed the iterative search, I had to un-indent my "return None" on line 66. All tests for those two are passing.
