### ISSUE TITLE
Feedback on palindrome and string algorithms

### ISSUE THREAD

**Issue by Anisha7** [JericHunter/CS-1.3-Core-Data-Structures#2]
**Palindromes**
Great work on your palindrome methods. Challenge yourself by implementing anagram generating function and writing new tests.

**Strings**
Great work on your strings algorithm. Looks like a small indentation error prevents your code from being compiled on line 31 in strings.py. Fix this and push to GitHub so your code doesn't break! 

Additionally, work on refactoring (does find_all_indices have code you have already written for another method?), annotating space/time complexities and writing additional unit tests for full credit.

**Comment by JericHunter** [comment]
Fixed errors and added additional tests
